### PR TITLE
Create skeleton ansible-cli python script for review; include options or shell_init

### PR DESCRIPTION
**Pull request by mbrannigan**
@clintoncwolfe - Let me know what ya think.  It's includes some skeleton for generate as well as some functionality for shell_init.

### CODE REVIEW

**Comment by clintoncwolfe** [comment]
I added click 5.1 to the omnibus build.  On my machine, with the ansible DK installed and my env vars set (using the bash shell-init), I now have:

```
[clinton@and-cheese ~]$ /opt/ansible-dk/embedded/bin/pip list
awscli (1.9.5)
boto (2.36.0)
botocore (1.3.5)
click (5.1)
colorama (0.3.3)
docutils (0.12)
jmespath (0.9.0)
pip (7.1.2)
pyasn1 (0.1.9)
python-dateutil (2.4.2)
rsa (3.2.3)
setuptools (18.5)
six (1.10.0)
[clinton@and-cheese ~]$ ls /opt/ansible-dk/embedded/lib/python2.7/site-packages/click-5.1-py2.7.egg-info
PKG-INFO        dependency_links.txt    top_level.txt
SOURCES.txt     installed-files.txt
```

**Comment by mbrannigan** [comment]
@clintoncwolfe I made the recommended changes.  I'm currently on MacOS Yosemite, but I can develop in Ubuntu 14.04 LTS.

**Comment by mbrannigan** [comment]
I'm not quite familiar with omnibus.  Is there any documentation or things I can take a look at to become more familiar with it?

**Comment by mbrannigan** [comment]
@clintoncwolfe I'm starting up an ubuntu 14.04 box up to work with the omnibus

**Comment by clintoncwolfe** [comment]
You can learn about omnibus here - https://github.com/chef/omnibus - basically, you:
- make sure you have a ruby installed, 2.1 or later I suspect
- clone the repo
- cd omnibus-ansible-dk
- bundle install (cross fingers)
- bundle exec omnibus build ansible-dk
  The first time, it will fail, wanting to write to odd places under /var and /opt/ansible-dk (I think it's pretty sloppy in this regard).  Make the directories, and have them writable by you.  Then it "should" work -though a build will likely take 15-30 minutes.  If all goes well, you'll have a dmg file in pkg/ .

For ubuntu 14.04, we've made a test kitchen file that does the whole thing - sets up omnibus, then runs the build.  It by default uses vagrant+virtualbox locally, but if you know some test kitchen, you can replace that with an AWS config.  

Or, skip all that, and just use these "nightlies" we made today:
https://bintray.com/omniti-labs/ansible-dk/ansible-dk/view

If you install that DMG, it will unpack a bunch of stuff to /opt/ansible-dk, and link /usr/local/bin/ansible-dk to the existing bash version of the CLI.  Then you can 'eval "$(ansible-dk shell-init bash)"' to get your paths set, and should be able to develop against the "captive" python and click.

**Comment by clintoncwolfe** [comment]
Hey, don't mean to let this languish - do you still consider this a "request for review" PR, or do you feel it's ready to merge?

**Comment by clintoncwolfe** [comment]
Will need similar change to PATH as #45

**Comment by clintoncwolfe** [comment]
Closing this PR, integration of this work is continuing on #56

**Pull request closed without merging**
